[INFO] (2016-11-11 12:04:55,496) Config file successfully read
[INFO] (2016-11-11 12:04:55,518) Connection to database 'TEMPLeidos' successful
[INFO] (2016-11-11 12:04:55,519) Database 'TEMPLeidos' successfully initialized
[INFO] (2016-11-11 12:04:55,519) Starting tokenizer
[INFO] (2016-11-11 12:04:55,519) Project ids start at 2700000028 and file ids start at 118
[INFO] (2016-11-11 12:04:55,519) Editing tokenizer config file in 'bin/tokenizer/config.ini'
[INFO] (2016-11-11 12:04:55,519) Starting tokenizer, output in 'bin/tokenizer/output-1478894695.52'
[ERROR] (2016-11-11 12:04:55,540) An error occured on the tokenizer
[ERROR] (2016-11-11 12:04:55,540) Command 'python bin/tokenizer/tokenizer.py' returned non-zero exit status 1
[INFO] (2016-11-11 12:04:55,540) Tokenizer finished
